import { ArrowRight, Database, GitBranch, Play, Presentation, ShieldCheck, Sparkles } from "lucide-react";
import { useOptionalPresentation } from "../../i18n";
import { useShowcase } from "../../state/ShowcaseState";
import type { RuntimeTraceV1 } from "../../types/runtimeTrace";
import { EXECUTIVE_ARCHITECTURE, EXECUTIVE_CAPABILITIES, buildExecutiveStory } from "../adapters/executiveRuntime";
import { Badge, Button, EmptyState, KeyValue, Metric, Panel, StatusBadge } from "../components/Primitives";
import { useControlCenter } from "../state/ControlCenterState";
import { useRuntimeStatus } from "../state/RuntimeStatusState";

const shortId=(value?:string|null)=>value?`${value.slice(0,8)}…`:"Unavailable";
const ms=(value?:number|null)=>value==null?"Unavailable":value>=1000?`${(value/1000).toFixed(2)} s`:`${value.toFixed(1)} ms`;
const outcomeTone=(trace:RuntimeTraceV1):"completed"|"refused"|"failed"|"partial"=>trace.outcome.status==="refused"?"refused":trace.trace.status==="failed"?"failed":trace.trace.status==="partial"?"partial":"completed";
const stageTone=(state:string):"completed"|"refused"|"failed"|"partial"|"unavailable"=>state==="refused"?"refused":state==="failed"?"failed":state==="partial"?"partial":["skipped","not_applicable","unavailable","not_started"].includes(state)?"unavailable":"completed";

type Copy=ReturnType<typeof copyFor>;
function copyFor(zh:boolean){return zh?{
  pageTitle:"Showcase / Executive View",pageDetail:"面向领导、面试与录屏的 OPK-RAG 执行解释视图；与工程页面共享同一条权威 Runtime Trace。",presentation:"正式展示视图",
  heroEyebrow:"OPK-RAG · EXECUTIVE VIEW",heroTitle:"一个能够解释自身执行过程的受控个人知识库 RAG。",heroBody:"混合检索、受控 Agent 恢复、one-hop Graph Retrieval、BGE 重排序、Evidence 血缘以及 Grounding / Citation 验证。",
  heroTraceTitle:"个人知识检索 + 受控恢复 + Evidence-first 回答验证。",heroTraceBody:"面向中文个人知识库：缺少结构时受控恢复，存在权威跨文件关系时只走一跳 Graph；所有 Candidate 回到统一 BGE Rerank，答案只有经过 Evidence、Grounding 与 Citation 边界才释放。",
  currentOutcome:"当前结果",currentExecution:"本次执行",sameTrace:"同一条 active Runtime Trace",whatHappened:"这次发生了什么？",runtimeStoryboard:"本次 Query 的执行路径",runtimeTrace:"Runtime Trace V1",
  recoveryGraph:"Recovery / Graph 贡献",evidenceSafety:"Evidence 与回答安全",evidenceSupported:"真正支撑本次执行的 Evidence",architecture:"系统架构",architectureBadge:"能力地图 · 不代表本次 Query 全部执行",engineering:"工程运行环境",governance:"治理边界",
  recovery:"恢复动作",recovered:"恢复 Candidate",evidence:"Evidence",citations:"Citation",total:"总耗时",outcome:"结果",safeRefusal:"安全拒答",refusedNotFailed:"Refused ≠ Failed · 这是受控释放结果",groundingPassed:"Grounding 已基于权威 Evidence 通过",
  hop:"Hop",recoveredCandidates:"恢复 Candidate",graphLineage:"权威 one-hop Graph relation → recovered Candidate → Evidence / Citation。",noGraph:"Guarded Agent 在此 Trace 中没有执行 Graph Recovery。",structurePrefix:"Structure Recovery 将观察到的 Candidate Pool 从",
  inspectRuntime:"查看 Runtime",inspectGraph:"查看 Graph",inspectEvidence:"查看 Evidence",enoughEvidence:"Evidence 足够？",generate:"Generation",grounded:"Grounding",release:"Release",searchEvidence:"Search 已选择 Evidence",yes:"是",no:"否",abstained:"Abstained",completed:"Completed",passed:"Passed",
  candidateBoundary:"Candidate ≠ Evidence ≠ Citation",graphRecovered:"Graph recovered",cited:"已引用",noEvidence:"无 Evidence 记录",noEvidenceDetail:"当前 Trace 没有权威 Evidence item；Showcase 不会从答案文本反向构造 Evidence。",
  vectorDb:"向量库",embedding:"Embedding",reranker:"Reranker",generation:"Generation",gpu:"GPU",knowledgeBase:"知识库",graphFreshness:"Graph freshness",historicalMixed:"混入历史 benchmark",
  frozenScenarios:"冻结 Demo 场景",selectionExecution:"选择 ≠ 执行",running:"执行中…",runDemo:"运行 Demo",scenarioBoundary:"选择场景只改变 presentation selection。只有明确点击“运行 Demo”才会通过既有 Showcase API 执行 Runtime。",
  noTrace:"当前没有 Runtime Trace",noTraceDetail:"先运行 Search、Ask、Conversation turn，或显式运行冻结 Demo 场景。空闲态不会伪造任何 Runtime 指标。",runningNew:"正在运行新的执行",runningNewDetail:"等待新的权威 Runtime Trace。旧 Trace 不会被冒充为本次结果，未来阶段也不会被预填或模拟。",
}:{
  pageTitle:"Showcase / Executive View",pageDetail:"A presentation-focused explanation of the active OPK-RAG execution using the same authoritative Runtime Trace.",presentation:"Executive presentation",
  heroEyebrow:"OPK-RAG · EXECUTIVE VIEW",heroTitle:"A governed personal-knowledge RAG, built to explain its own execution.",heroBody:"Hybrid retrieval, bounded Agent recovery, one-hop Graph Retrieval, BGE reranking, Evidence lineage, Grounding and Citation validation.",
  heroTraceTitle:"Personal knowledge retrieval with governed recovery and evidence-first answer validation.",heroTraceBody:"A local-first Chinese RAG system that can recover missing structure, follow authoritative one-hop relations, rerank all Candidates, and release answers only through Evidence, Grounding and Citation gates.",
  currentOutcome:"Current outcome",currentExecution:"Current Execution",sameTrace:"same active Runtime Trace",whatHappened:"What happened?",runtimeStoryboard:"This Query's Execution",runtimeTrace:"Runtime Trace V1",
  recoveryGraph:"Recovery / Graph Story",evidenceSafety:"Evidence & Answer Safety",evidenceSupported:"Evidence That Supported This Execution",architecture:"System Architecture",architectureBadge:"Capability map · not this query's execution",engineering:"Engineering Runtime",governance:"Governance Boundaries",
  recovery:"Recovery",recovered:"Recovered",evidence:"Evidence",citations:"Citations",total:"Total",outcome:"Outcome",safeRefusal:"Safe refusal",refusedNotFailed:"Refused ≠ failed · governed release behavior",groundingPassed:"Grounding passed against authoritative Evidence",
  hop:"Hop",recoveredCandidates:"Recovered Candidates",graphLineage:"Authoritative one-hop Graph relation → recovered Candidate → downstream Evidence / Citation when present.",noGraph:"The Guarded Agent did not execute Graph Recovery for this trace.",structurePrefix:"Structure Recovery expanded the observed pool",
  inspectRuntime:"Inspect Runtime",inspectGraph:"Inspect Graph",inspectEvidence:"Inspect Evidence",enoughEvidence:"Enough Evidence?",generate:"Generate",grounded:"Grounded?",release:"Release",searchEvidence:"Search selected Evidence",yes:"Yes",no:"No",abstained:"Abstained",completed:"Completed",passed:"Passed",
  candidateBoundary:"Candidate ≠ Evidence ≠ Citation",graphRecovered:"Graph recovered",cited:"Cited",noEvidence:"No Evidence records",noEvidenceDetail:"This trace contains no authoritative Evidence items; the Showcase does not reconstruct them from answer text.",
  vectorDb:"Vector DB",embedding:"Embedding",reranker:"Reranker",generation:"Generation",gpu:"GPU",knowledgeBase:"Knowledge Base",graphFreshness:"Graph freshness",historicalMixed:"Historical mixed",
  frozenScenarios:"Frozen Demo Scenarios",selectionExecution:"Selection ≠ execution",running:"Running…",runDemo:"Run Demo",scenarioBoundary:"Selecting a scenario only changes presentation selection. Runtime execution happens only after the explicit Run Demo action through the existing Showcase API.",
  noTrace:"No active Runtime Trace",noTraceDetail:"Run Search, Ask, a Conversation turn, or an explicit frozen Demo scenario to create an execution story. No runtime metrics are fabricated while idle.",runningNew:"Running new execution",runningNewDetail:"Waiting for the next authoritative Runtime Trace. A previous trace is not presented as the current execution, and future stages are not prefilled or simulated.",
};}


function presentationMessages(trace:RuntimeTraceV1, story:ReturnType<typeof buildExecutiveStory>, zh:boolean):string[]{
  if(!zh) return story.messages;
  const rows:string[]=[];
  if(story.recoveryKind==="none") rows.push("初始检索已经足够，因此受控 Guarded Agent 保持普通路径，没有为了展示智能而执行不必要的 Recovery。");
  if(story.recoveryKind==="structure") rows.push(`系统在重排序前执行一次受控 Structure Recovery；观察到的 Candidate Pool 从 ${trace.structure_recovery.candidate_pool_count_before??"?"} 扩展到 ${trace.structure_recovery.candidate_pool_count_after??"?"}。`);
  if(story.recoveryKind==="graph") rows.push(`系统执行权威 one-hop Graph Recovery，在统一 BGE Rerank 前恢复 ${trace.graph_recovery.recovered_candidate_count??"?"} 个 Candidate。`);
  if(trace.query.execution_scope==="search") rows.push("Search 的执行范围在 Evidence 结束；本 Trace 不会伪造 Generation、Grounding 或 Citation 阶段。");
  else if(story.safeRefusal) rows.push("Evidence 存在且 Answerability 通过，但 Generation 主动 abstain；系统选择安全拒答，而不是强行释放答案。");
  else if(trace.grounding.grounding_passed===true) rows.push("生成结果在释放前已经基于选定 Evidence 通过 Grounding 与 Citation 验证。");
  else if(trace.trace.status==="failed") rows.push("执行在权威 Runtime stage 失败；Showcase 不会合成成功叙事。");
  return rows;
}
function presentationStage(stage:ReturnType<typeof buildExecutiveStory>["stages"][number], zh:boolean){
  if(!zh) return stage;
  const labels:Record<string,string>={retrieve:"检索",guard:"Guard",recover:"恢复",rerank:"重排序",evidence:"Evidence",validate:"验证",outcome:"回答 / 拒答"};
  const detail=stage.detail
    .replace("Recovery required","需要 Recovery").replace("Normal path","普通路径")
    .replace("Structure Recovery","Structure Recovery").replace("No Recovery","无需 Recovery")
    .replace("Search scope · N/A","Search 范围 · N/A").replace("Generation abstained","Generation abstained")
    .replace("Grounding passed","Grounding 通过").replace("Safe refusal","安全拒答").replace("Search complete","Search 完成").replace("Answered","已回答");
  return {...stage,label:labels[stage.id]||stage.label,detail};
}

function ArchitectureStory({c}:{c:Copy}){return <Panel title={c.architecture} action={<Badge tone="info">{c.architectureBadge}</Badge>}><div className="cc-exec-architecture" aria-label="OPK-RAG system architecture">{EXECUTIVE_ARCHITECTURE.map((stage,index)=><div className="cc-exec-architecture-fragment" key={stage}><span>{stage}</span>{index<EXECUTIVE_ARCHITECTURE.length-1&&<ArrowRight size={14} aria-hidden="true"/>}</div>)}</div></Panel>}
function CapabilityStrip(){return <div className="cc-exec-capabilities">{EXECUTIVE_CAPABILITIES.map(([name,detail])=><div key={name}><strong>{name}</strong><span>{detail}</span></div>)}</div>}
function ScenarioLauncher({c}:{c:Copy}){const {state,actions}=useShowcase();const selected=state.scenarios.find(s=>s.scenario_id===state.selectedScenarioId);return <Panel title={c.frozenScenarios} action={<Badge tone="info">{c.selectionExecution}</Badge>}><div className="cc-exec-scenario-toolbar"><div className="cc-exec-scenarios" role="group" aria-label="Showcase scenario selection">{state.scenarios.map(s=><button type="button" key={s.scenario_id} data-selected={s.scenario_id===state.selectedScenarioId} onClick={()=>actions.selectScenario(s.scenario_id)}><strong>{s.scenario_id}</strong><span>{s.title||s.name||s.description||"Frozen scenario"}</span></button>)}</div><Button variant="primary" disabled={!selected||state.lifecycle==="executing"} onClick={()=>void actions.runSelectedScenario()}><Play size={14}/>{state.lifecycle==="executing"?c.running:c.runDemo}</Button></div><div className="cc-inspector-boundary-note">{c.scenarioBoundary}</div></Panel>}
function EmptyExecutive({c}:{c:Copy}){return <div className="cc-exec-stack" data-showcase-authority="no-active-trace"><section className="cc-exec-hero cc-exec-hero-empty"><div><span className="cc-exec-eyebrow">{c.heroEyebrow}</span><h1>{c.heroTitle}</h1><p>{c.heroBody}</p></div><Presentation size={34} aria-hidden="true"/></section><CapabilityStrip/><Panel><EmptyState title={c.noTrace} detail={c.noTraceDetail}/></Panel><ArchitectureStory c={c}/><ScenarioLauncher c={c}/></div>}

function ExecutiveTrace({trace,c}:{trace:RuntimeTraceV1;c:Copy}){
  const control=useControlCenter();const runtime=useRuntimeStatus();const story=buildExecutiveStory(trace);const zh=useOptionalPresentation()?.locale==="zh-CN";const messages=presentationMessages(trace,story,zh);const stages=story.stages.map(stage=>presentationStage(stage,zh));const status=runtime.state.status;const graph=story.graph;const query=trace.query.query_text||trace.query.normalized_query||"Query unavailable";const recovered=trace.graph_recovery.recovered_candidate_count??trace.structure_recovery.expanded_candidate_count??0;
  return <div className="cc-exec-stack" data-showcase-authority="active-runtime-trace" data-presentation-mode={control.state.mode}>
    <section className="cc-exec-hero" data-outcome={story.status}><div className="cc-exec-hero-copy"><span className="cc-exec-eyebrow">{c.heroEyebrow}</span><h1>{c.heroTraceTitle}</h1><p>{c.heroTraceBody}</p><div className="cc-exec-badges"><Badge>Qdrant</Badge><Badge>Hybrid Retrieval</Badge><Badge>Guarded Agent</Badge><Badge>GraphRAG · 1 hop</Badge><Badge>BGE Reranker</Badge><Badge>Grounded Citations</Badge></div></div><div className="cc-exec-outcome"><span>{c.currentOutcome}</span><strong>{story.safeRefusal?"SAFE REFUSAL":story.status.toUpperCase()}</strong><StatusBadge status={outcomeTone(trace)} label={trace.outcome.answer_status||story.status}/><small className="cc-mono">trace {shortId(trace.trace.trace_id)}</small></div></section>
    <CapabilityStrip/>
    <div className="cc-exec-query-grid"><Panel title={c.currentExecution} action={<Badge tone="info">{c.sameTrace}</Badge>}><div className="cc-exec-query"><span>{story.scope.toUpperCase()}</span><h2>{query}</h2></div><div className="cc-exec-kpis"><Metric label={c.recovery} value={story.recoveryLabel}/><Metric label={c.recovered} value={recovered}/><Metric label={c.evidence} value={trace.evidence.evidence_count??"Unavailable"}/><Metric label={c.citations} value={trace.citation.citation_count??(trace.query.execution_scope==="search"?"N/A":"Unavailable")}/><Metric label={c.total} value={ms(trace.timings.total_ms)}/><Metric label={c.outcome} value={story.safeRefusal?c.safeRefusal:trace.outcome.answer_status||story.status}/></div></Panel><Panel title={c.whatHappened} action={<Sparkles size={16} aria-hidden="true"/>}><div className="cc-exec-narrative">{messages.map((message,index)=><div key={`${index}-${message}`}><span>{index+1}</span><p>{message}</p></div>)}</div>{story.safeRefusal&&<div className="cc-exec-assurance refused"><ShieldCheck size={15}/>{c.refusedNotFailed}</div>}{trace.grounding.grounding_passed===true&&<div className="cc-exec-assurance"><ShieldCheck size={15}/>{c.groundingPassed}</div>}</Panel></div>
    <Panel title={c.runtimeStoryboard} action={<Badge tone="info">{c.runtimeTrace}</Badge>}><div className="cc-exec-storyboard" aria-label="Executive Runtime Storyboard">{stages.map((stage,index)=><div className="cc-exec-story-fragment" key={stage.id}><div className="cc-exec-story-stage" data-state={stage.state}><span>{stage.label}</span><strong>{stage.detail}</strong><StatusBadge status={stageTone(stage.state)} label={stage.state}/></div>{index<story.stages.length-1&&<ArrowRight size={15} aria-hidden="true"/>}</div>)}</div></Panel>
    <div className="cc-exec-two-column"><Panel title={c.recoveryGraph} action={<GitBranch size={16} aria-hidden="true"/>}>{graph.active?<><div className="cc-exec-graph-line"><span>{graph.source||"Source node"}</span><strong>{graph.relation||"RELATION"}</strong><span>{graph.target||"Target node"}</span></div><div className="cc-exec-graph-facts"><Metric label={c.hop} value={graph.hop??"Unavailable"}/><Metric label={c.recoveredCandidates} value={graph.recoveredCandidates??"Unavailable"}/><Metric label="Evidence" value={graph.evidenceId||"Unavailable"}/><Metric label="Citation" value={graph.citationId||"Unavailable"}/></div><p className="cc-muted">{c.graphLineage}</p></>:<div className="cc-exec-recovery-state"><ShieldCheck size={20}/><strong>{story.recoveryLabel}</strong><span>{story.recoveryKind==="structure"?`${c.structurePrefix} ${trace.structure_recovery.candidate_pool_count_before??"?"} → ${trace.structure_recovery.candidate_pool_count_after??"?"}.`:c.noGraph}</span></div>}<div className="cc-inline-actions cc-exec-drilldowns"><Button onClick={()=>control.actions.setActiveNav("runtime")}>{c.inspectRuntime}</Button>{graph.active&&<Button onClick={()=>control.actions.setActiveNav("graph")}>{c.inspectGraph}</Button>}<Button variant="primary" onClick={()=>control.actions.setActiveNav("evidence")}>{c.inspectEvidence}</Button></div></Panel>
    <Panel title={c.evidenceSafety} action={<ShieldCheck size={16} aria-hidden="true"/>}><div className="cc-exec-validation-chain"><div><span>{c.enoughEvidence}</span><strong>{trace.query.execution_scope==="search"?c.searchEvidence:trace.answerability.answerable==null?"Unavailable":trace.answerability.answerable?c.yes:c.no}</strong></div><ArrowRight size={14}/><div><span>{c.generate}</span><strong>{trace.query.execution_scope==="search"?"N/A":trace.generation.generation_abstained?c.abstained:trace.generation.generation_completed?c.completed:trace.generation.stage_state||"Unavailable"}</strong></div><ArrowRight size={14}/><div><span>{c.grounded}</span><strong>{trace.query.execution_scope==="search"?"N/A":trace.grounding.grounding_passed?c.passed:trace.grounding.status||"Unavailable"}</strong></div><ArrowRight size={14}/><div><span>{c.release}</span><strong>{story.safeRefusal?c.safeRefusal:trace.outcome.answer_status||story.status}</strong></div></div>{trace.grounding.citation_coverage!=null&&<KeyValue label="Citation coverage (not correctness)">{Math.round(trace.grounding.citation_coverage*100)}%</KeyValue>}</Panel></div>
    <Panel title={c.evidenceSupported} action={<Badge tone="info">{c.candidateBoundary}</Badge>}>{story.evidence.length?<div className="cc-exec-evidence-grid">{story.evidence.map((item,index)=><article key={`${item.evidenceId}-${index}`} data-graph-recovered={item.graphRecovered}><header><strong>{item.document}</strong>{item.cited&&<Badge tone="success">{c.cited}</Badge>}</header><span>{item.section}</span><small>{item.lines} · {item.provenance}</small>{item.graphRecovered&&<div className="cc-exec-lineage"><Badge>{c.graphRecovered}</Badge><ArrowRight size={12}/><span>{item.evidenceId||"Evidence"}</span><ArrowRight size={12}/><span>{graph.citationId||"Citation"}</span></div>}</article>)}</div>:<EmptyState title={c.noEvidence} detail={c.noEvidenceDetail}/>}</Panel>
    <ArchitectureStory c={c}/>
    <Panel title={c.engineering} action={<Database size={16} aria-hidden="true"/>}><div className="cc-exec-infrastructure"><Metric label={c.vectorDb} value={trace.runtime.vector_backend||status?.qdrant.backend||"Unavailable"}/><Metric label={c.embedding} value={trace.runtime.embedding_model||status?.models.embedding?.model||"Unavailable"}/><Metric label={c.reranker} value={trace.rerank.reranker_model||status?.models.reranker?.model||"Unavailable"}/><Metric label={c.generation} value={trace.generation.generation_model||status?.models.generation?.model||"Unavailable"}/><Metric label={c.gpu} value={status?.gpu.device_name||"Unavailable"}/><Metric label={c.knowledgeBase} value={status?.knowledge_base.indexed_document_count==null?"Unavailable":`${status.knowledge_base.indexed_document_count} docs`}/><Metric label={c.graphFreshness} value={status?.graph.graph_freshness||"Unavailable"}/><Metric label={c.historicalMixed} value={String(trace.timings.historical_benchmark_values_mixed_into_live_trace===true)}/></div></Panel>
    <Panel title={c.governance}><div className="cc-exec-governance"><span>Graph max hop = 1</span><span>Recovery max = 1</span><span>UI authority = false</span><span>Graph Node ≠ Candidate</span><span>Candidate ≠ Evidence</span><span>Evidence ≠ Citation</span><span>Answerability ≠ forced Generation</span><span>Refused ≠ Failed</span></div></Panel><ScenarioLauncher c={c}/>
  </div>;
}

export function ShowcaseExecutivePage(){const {state}=useShowcase();const presentation=useOptionalPresentation();const c=copyFor(presentation?.locale==="zh-CN");return <div className="cc-page cc-showcase-page" data-modern-showcase="active" data-recording={Boolean(presentation?.recordingMode)}><header className="cc-page-heading"><div><h1 className="cc-title">{c.pageTitle}</h1><p>{c.pageDetail}</p></div><Badge tone="info"><Presentation size={12}/> {c.presentation}</Badge></header>{state.lifecycle==="executing"?<Panel><EmptyState title={c.runningNew} detail={c.runningNewDetail}/></Panel>:state.trace?<ExecutiveTrace trace={state.trace} c={c}/>:<EmptyExecutive c={c}/>}</div>}
